name: Build

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install / Build
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build --if-present
      - run: pnpm test
      - run: cd dist && npm link

      # packages/starter
      - run: pnpm link @rectangulr/rectangulr && pnpm run build && pnpm run test
        working-directory: ./packages/starter

      # Version / Publish
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
