name: Build

on:
  push:
    branches: ['**']


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

      # Setup
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2

      - name: "Install Dependencies"
        run: "bun i --include=dev"
      - name: "Rectangulr CI"
        run: "bun i zx && bun ci.mts"
