name: Publish
on:
  workflow_run:
    workflows: [Build]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: npm set "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}"

      - run: npm ci --include=dev
        working-directory: ./packages/rectangulr
      - run: npm run build
        working-directory: ./packages/rectangulr

      # Publish
      - name: Publish
        run: bash ./packages/rectangulr/dev/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Create Release Pull Request or Publish
      #   uses: changesets/action@v1
      #   with:
      #     publish: bash ./packages/rectangulr/dev/publish.sh
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm ci --include=dev
        working-directory: ./packages/buildr
      - run: npm run build
        working-directory: ./packages/buildr
      - name: Publish
        run: np publish-if-not-exists
        working-directory: ./packages/buildr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

